name: Autograding

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile test.cpp
        run: g++ -std=c++17 test.cpp -o test

      - name: Run tests
        run: ./test
